apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: dev-team
  description: "Adaptive Space Team"
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/my-org/my-repo/blob/master/dev-team.yaml"
spec:
  type: team
  profile:
    displayName: "Adaptive Space Team"
    email: adaptive-space-team@westpac.com.au
  parent: my-org
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: digital-banking
  tags:
    - westpac
spec:
  owner: adaptive_space_team 
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: pgs-adaptive-space-01
  description: "pgs-adaptive-space-01"
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/my-org/my-repo/blob/master/database.yaml"
spec:
  type: database
  owner: dev-team
  lifecycle: production
  system: digital-banking
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: npp-transfer-api
  description: "npp-transfer-api"
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/my-org/my-repo/blob/master/my-grpc-api.yaml"
spec:
  type: grpc
  lifecycle: production
  owner: dev-team
  system: digital-banking
  definition: |
    syntax = "proto3";
    package myorg.mygrpcapi;
    message MyRequest {
      string query = 1;
    }
    message MyResponse {
      string result = 1;
    }
    service MyGrpcApi {
      rpc MyMethod (MyRequest) returns (MyResponse);
    }
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: digital-banking-backend
  description: "Globex Backend Service"
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/my-org/my-repo/blob/master/my-backend.yaml"
spec:
  type: service
  lifecycle: production
  owner: dev-team
  system: digital-banking
  dependsOn:
    - resource:globex-database
  providesApis:
    - npp-transfer-api
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: digital-banking-frontend
  description: "Globex Frontend"
  annotations:
    backstage.io/managed-by-location: "url:https://github.com/my-org/my-repo/blob/master/my-frontend.yaml"
spec:
  type: service
  lifecycle: production
  owner: dev-team
  system: digital-banking
  consumesApis:
    - npp-transfer-api
